### ISSUE TITLE
Can't set IPv6 when VM have multiple NICs

### ISSUE THREAD

**Issue by vynt-kenshiro** [OpenNebula/addon-context-windows#15]
Hello,

I found a small bug on this script. I have 3 NIC with 2st NIC only have a IPv6 address. After run context.ps1 script then 2st and 3st NIC not configured. I solve the issue  by modify conditional on configureNetwork function. I think you should update context.ps1 script.

```
function configureNetwork($context) {
    $nicId = 0;
    $nicIpKey = "ETH" + $nicId + "_IP"
    $nicIpKey6 = "ETH" + $nicId + "_IP6"
    while ($context[$nicIpKey] -Or $context[$nicIpKey6]) {
    .... truncated ....
    
    	$nicId++;
        $nicIpKey = "ETH" + $nicId + "_IP"
        $nicIpKey6 = "ETH" + $nicId + "_IP6"
    }
}
```

**Comment by vholer** [comment]
Hi @vynt-kenshiro, the fix is done by commit 14c1a2f1dc710df1a95bf7e0fdfc18a4e97cc2e7. If you want, you can test it. I'm closing this issue for now, thank you for your report!
