### ISSUE TITLE
onecontext service binary is dated 01.01.1970

### ISSUE THREAD

**Issue by FlorianHeigl** [OpenNebula/addon-context-windows#28]
Hi,

there seems to be a little issue with how the binary for the onecontext service is generated.
If I look at it with SysInternal's "autoruns" tool then it will show the "second 0" date.

**Comment by vholer** [comment]
Hi @FlorianHeigl, can you please more describe a problem and steps to reproduce it? Are you trying to compile the rhsrvany on your own and there is some problem? Or, are you trying the MSI package and service is not correctly installed in the system? Maybe some screenshots can be also helpful. Thank you!

**Comment by FlorianHeigl** [comment]
Hey @vholer  :) 
I'll make screenshots etc. in a few days. it's already planned.
(I had used the MSI)

**Comment by vholer** [comment]
Hi @FlorianHeigl. Please, would you find some time to describe the problem more? Thank you!

**Comment by vholer** [comment]
I know what you mean, there is an invalid timestamp deep inside the EXE metadata. This is an issue for all cross-compiled EXEs on Red Hat.

```
# exiftool /usr/share/virt-tools/rhsrvany.exe -v
  ExifToolVersion = 10.40
  FileName = rhsrvany.exe
  Directory = .
  FileSize = 20228
  FileModifyDate = 1483550066
  FileAccessDate = 1496309294
  FileInodeChangeDate = 1483555568
  FilePermissions = 33152
  FileType = Win32 EXE
  FileTypeExtension = EXE
  MIMEType = application/octet-stream
  + [BinaryData directory, 248 bytes]
  | MachineType = 332
  | TimeStamp = 0
  | PEType = 267
  | LinkerVersion = 2 25
  | CodeSize = 8192
  | InitializedDataSize = 15360
  | UninitializedDataSize = 1536
  | EntryPoint = 5344
  | OSVersion = 4 0
  | ImageVersion = 1 0
  | SubsystemVersion = 4 0
  | Subsystem = 3
```

I think it's better to stick with their (working) binary than compile it ourselves. And also I'm not sure about patching the EXE metadata... Hmm, I guess it doesn't cause any problems in real use, right?

**Comment by vholer** [comment]
Depends on a binary which is built by a 3rd party, closing for now.
