### ISSUE TITLE
Support DNS_HOSTNAME

### ISSUE THREAD

**Issue by vholer** [OpenNebula/addon-context-windows#36]
Example https://forum.opennebula.org/t/getting-dns-hostname-to-work-in-windows/4945,
but better use e.g. `[System.Net.Dns]::GetHostbyAddress("8.8.8.8").HostName`

**Comment by vizonyc** [comment]
Well I see the code has changed since I tried to get dns hostname to work has there been any word on adding this functionality? reasoning: If I spin up multiple windows boxes at the same time I just need to set dns for all of them first for host naming

**Comment by ospalax** [comment]
Done by PRs:
- https://github.com/OpenNebula/addon-context-windows/pull/80
- https://github.com/OpenNebula/docs/pull/1155
