### ISSUE TITLE
New attached NIC doesn't assign IP util reboot

### ISSUE THREAD

**Issue by baohuy1204** [OpenNebula/addon-context-windows#40]
When attach new NIC to VM, the new attached NIC does not assign IP correctly util restart or I have to run this command manually:
`powershell.exe -ExecutionPolicy Unrestricted -file 'C:\Program Files (x86)\OpenNebula\context.ps1'`

Can new attached NIC assign IP automatically without reboot or run command manually?

**Comment by vholer** [comment]
Unfortunately, the contextualization is run just once on boot (or, if manually triggered). Right now, there is no support to automatically recontextualize on new NIC attach. Marking as an enhancement request for the future releases.

**Comment by ospalax** [comment]
Hi, this is implemented by PR: https://github.com/OpenNebula/addon-context-windows/pull/89
