### ISSUE TITLE
Set IP issue with Windows 2008 R2

### ISSUE THREAD

**Issue by levinng** [OpenNebula/addon-context-windows#5]
The script was unable to set IP address properly on Windows 2008 R2, the DNS, and gateways were fine, however the IP wasn't. 

Remove the line from the script that workaround this problem. It looks a time race between release IP and set the IP where the vNIC has not yet been ready for set manual IP address.

$nic.ReleaseDHCPLease()

**Comment by vholer** [comment]
@levinng, thank you for reporting the problem and we're sorry for the delay. Looks like you were experiencing a rare race condition. The `releaseDHCPLease()` isn't most likely the synchronous operation and can take longer than expected. I'm not absolutely sure if skipping the release is a good option for other people, so I propose following simple changes:

1. first check if the interface is DHCP configured
2. call `releaseDHCPLease()`
3. check and wait until the interface is ready (unconfigured)

(inspired by http://www.isolation.se/change-mac-address-with-powershell-of-a-wireless-adapter/)

**Comment by vholer** [comment]
@levinng I have played with that a little on my Windows 7 and there is most likely problem with acquiring the write lock on `EnableStatic()`. New IP address, in your case, probably wasn't taken back by the `releaseDHCPLease()`. New IP address wasn't set at all. I have added simple retry mechanism. Thanks.

**Comment by vholer** [comment]
Fixed by 8bca15d1fdece483059de8030657a0b463386526, closing. Thank you.
