### ISSUE TITLE
INIT_SCRIPTS not run when using VMWare Tools

### ISSUE THREAD

**Issue by jeremyoverman** [OpenNebula/addon-context-windows#52]
If we end up using the VMWare tools to pull the context information instead of the CONTEXT ISO, the `$contextLetter` variable never gets set. I'd expect this to get set up `$env:SystemDrive\`. Without this being set, scripts declared in the `runScripts` function don't run because the this doesn't set the path correctly:

https://github.com/OpenNebula/addon-context-windows/blob/d25022ac819812855f55d7e307465e95be904e7b/context.ps1#L664

https://github.com/OpenNebula/addon-context-windows/blob/d25022ac819812855f55d7e307465e95be904e7b/context.ps1#L550

**Comment by ospalax** [comment]
Hi, you are correct that `$contextLetter` variable is empty in the case of VMWare and no CD-ROM but that does not need to be an issue if each script inside the `INIT_SCRIPTS` variable is an absolute path - e.g.: `C:\custom-init.d\rc1.ps1`

Correct me if I am wrong or I misunderstood something.

Either way I am tackling this issue in another PR: https://github.com/OpenNebula/addon-context-windows/pull/89

It will check if the script is absolute path and if it is then it will use this path unmodified but if the script path is relative then it will be prefixed as you suggested here.

Hopefully by doing it like this I don't break anyone's code - who used absolute paths to workaround this issue should be unaffected and the others now can enjoy your solution.

If my change does not solve your issue feel free to reopen this and update your PR to resolve the merging conflicts.

Thanks

**Comment by vholer** [comment]
I'm partially reopening this issue as I see 2 problems:

- `INIT_SCRIPTS` are not implemented for the VMware, it should pass custom script from OpenNebula (files datastore) to the VM and this doesn't work yet now.

- @jeremyoverman, even with @ospalax 's fix, looks to me like you are misusing the `INIT_SCRIPTS` parametr for a different behaviour. If you need to run the custom script, which is already inside the VM image, you should use `START_SCRIPT`.

**Comment by jeremyoverman** [comment]
Thanks for taking a look at this. I'm not in a position where I can test out changes with OpenNebula anymore, but based on @vholer's description it sounds like `START_SCRIPT` is what I was actually looking for here.

**Comment by vholer** [comment]
Implemented as part of #91
