### ISSUE TITLE
Remove passwords from context file after contextualization finishes 

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/addon-context-windows#67]
Leave the passwords in the context file is a security vulnerability, so it would be would if they are removed after contextualization ends.

**Comment by maglub** [comment]
After contextualization is done (first boot), the file is no longer needed, am I right? So the c:\context.sh could be removed after the contextualization script has been run?

Other cloud systems have an option in the webgui, like: "start and force recustomization", which would then (in the case of opennebula) recreate the file again and set off a contextualization.

My experience with the current setup, is that the context.sh file appears after each reboot.

**Comment by maglub** [comment]
Is there a schedule for when this might be planned?

**Comment by bgmastermind** [comment]
how about ejecting the cd after contextualization. At least that's what I did, but I'm not sure if there is a way to get it mounted again from guest. If not, then this also works.

**Comment by maglub** [comment]
In our case, there is a file in C:\context.sh, not a virtual CD. Would it be possible to have an option that this file is deleted after contextualization?

**Comment by vholer** [comment]
Fixed by #83, context.sh is now removed from local disk.
