### ISSUE TITLE
Deploy SSH Keys for windows user

### ISSUE THREAD

**Issue by a31amit** [OpenNebula/addon-context-windows#78]
Since Windows also support now OpenSSH, it can be great that context support to deploy user ssh-keys for Administrator or common user. 

Documentation

- [x] Update [Windows Image KB](https://support.opennebula.pro/hc/en-us/articles/360042898271-How-to-Build-an-Image-for-Windows-Virtual-Machines) to include OpenSSH install.
  - [x] Add it to YouTube pinned comment as well 
- [x] Update [Context Section](https://docs.opennebula.io/6.6/management_and_operations/references/template.html#context-section) to include SSH_KEY support and WADMIN flag for admin/standard user on Windows context https://github.com/OpenNebula/docs/pull/2493.

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by dann1** [comment]
Reopening because automatic tests still need to be written
